# Generated by Django 6.1.1 on 2026-09-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nationalite', models.CharField(default='Togolaise', max_length=100)),
                ('profession', models.CharField(max_length=150)),
                ('lieu_emission', models.CharField(default='Lomé', help_text='Ville où la carte est établie', max_length=100)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, editable=False, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('taille_cm', models.PositiveSmallIntegerField(help_text='Taille en cm, ex: 180 pour 1,80 m')),
                ('groupe_sanguin', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('pere', models.CharField(blank=True, max_length=150)),
                ('mere', models.CharField(blank=True, max_length=150)),
                ('contact_urgence_nom', models.CharField(max_length=150)),
                ('contact_urgence_relation', models.CharField(blank=True, help_text='Ex: Père, Mère, Épouse...', max_length=100)),
                ('contact_urgence_telephone', models.CharField(max_length=30)),
            ],
        ),
    ]
