# Generated by Django 6.1.1 on 2026-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='contact_urgence_nom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='contact_urgence_relation',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='contact_urgence_telephone',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='groupe_sanguin',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='mere',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='pere',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='taille_cm',
        ),
        migrations.AddField(
            model_name='personne',
            name='groupe',
            field=models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieu_emission',
            field=models.CharField(default='Lomé', help_text='Lieu où la carte est établie', max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
    ]
